name: io_uring
description: Blazing fast async `dart:io` implementation based on `io_uring`

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: ^1.1.2

dev_dependencies:
  build: ^2.1.1
  build_runner: ^2.1.4
  extra_pedantic: ^1.5.0
  scratch_space: ^1.0.1

dependency_overrides:
  build_runner:
    # https://github.com/dart-lang/build/pull/3214
    path: /home/simon/programming/build/build_runner